### ISSUE TITLE
Does not follow the XDG directory specification

### ISSUE THREAD

**Issue by fleaz** [sbreitf1/gohome#14]
This tool will create a folder `.gohome` directly in my $HOME directory to save my Matrix login credentials.
This is a trend seen in many modern tools and will result in a messy homedir. According to  the [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), data like this should go to `$XDG_STATE_HOME`. Sticking to the correct folder will not only keep your homedir clean, but also will make tasks like defining excludes for your backup tool much easier, because you know that a folder like `.cache` is irrelevant and can be ignored.

Something like [adrg/xdg](https://github.com/adrg/xdg) will probably be useful here.

If we want to be nice to the user, the tool could check for the old file location, and copy the files to the new location or at least print a warning to make the migration easier :)

**Comment by sbreitf1** [comment]
Sure, send me a Pull request ;)
